### PR TITLE
Includes systemd config for centos

### PR DESCRIPTION
**Pull request by peterabbott**
Update the setup to support systemd for newer versions of centos

Because of a recent update to the JSON libs I have had to update Gemfile to fix the version for ruby 1.9.3

### CODE REVIEW

**Comment by peterabbott** [comment]
Puppet have rolled out a new version of the gem which is broken all the facter setup in the unit tests. Can't even get the master pre-fork to work

**Comment by jhoblitt** [comment]
I will try to get the plumbing working again today so this PR can be rebased.

**Comment by KrzysztofHajdamowicz** [comment]
Hi @jhoblitt, this PR is over 2 years old, will this PR be merged into mainline?

**Comment by jhoblitt** [comment]
Sure ;)

**Pull request merged**
