### PR TITLE
Introduce dedicated jvm args parameter (rebased)

### PR DESCRIPTION
**Pull request by fraenki**
This is basically a rebased version of #61.
I really hope it gets merged this time around. :)

### CODE REVIEW

**Comment by fraenki** [comment]
> All checks have failed

It wasn't me! :) Looks like there's something else broken in the CI test.

**Comment by fraenki** [comment]
Hi @jhoblitt, is there any chance to get this merged? Thanks! :)

**Comment by jhoblitt** [comment]
@fraenki Yes. This module desperately needs the test plumbing updated and I haven't gotten around to it.  If your willing to rebase on the current master I will merge the PR.

**Comment by fraenki** [comment]
@jhoblitt rebased and ready for merge :)

**Comment by jhoblitt** [comment]
Thank you!

**Pull request merged**
