### PR TITLE
Debian support

### PR DESCRIPTION
**Pull request by jshholland**
This is based on #17 with one small change to make the tests pass. Thanks to @dig412 for doing the hard work!

### CODE REVIEW

**Comment by jhoblitt** [comment]
Looks like the unit tests need to be changed.  Did you run the acceptance tests?

**Comment by jshholland** [comment]
If you mean "did I run `rake spec`", then yes. If not, no.

**Comment by jhoblitt** [comment]
I was referring to `rake beaker`.  Don't worry about it. Once you fixup the test failure I'll take a look.  Thanks for working on this.

**Comment by jshholland** [comment]
I changed the tests so that `rake beaker` passes with the default nodeset, as well as Ubuntu 14.04 and Debian 7.3.

**Comment by jhoblitt** [comment]
@jshholland Thanks for bringing this together!  There were a few minor issues which I fixed up and merged as #42.

**Comment by dig412** [comment]
Thanks for sorting this out everyone!

**Comment by jhoblitt** [comment]
Indeed.  Many thanks to all! https://twitter.com/jhoblitt/status/602678874086899714

**Pull request closed without merging**
