### PR TITLE
add support for systemd

### PR DESCRIPTION
**Pull request by dwerder**
This adds support for systemd.
The default behavior is to use sysv, which means that nothing will change for default configurations.

### CODE REVIEW

**Comment by jhoblitt** [comment]
@dwerder Could you rebase on the current master to see if it resolves the travis failuers?

**Comment by dwerder** [comment]
Ready to be merged ;-)

**Comment by jhoblitt** [comment]
@dwerder Thank you... I suppose I should run the acceptance tests before mering it huh? :)

**Comment by dwerder** [comment]
Maybe :D

**Comment by jhoblitt** [comment]
@dwerder I'm looking at merging this PR with acceptance test coverage.  It looks like the systemd service file needs to setup logging.

**Comment by jhoblitt** [comment]
@dwerder I'm sorry if my last comment wasn't clear.  The acceptance tests are not passing.

**Comment by jhoblitt** [comment]
@dwerder could you rebase on the current master?

**Comment by jhoblitt** [comment]
ping?

**Comment by jhoblitt** [comment]
Superseded by #70

**Pull request closed without merging**
