### PR TITLE
fixed issue #19 SSL error with wget

### PR DESCRIPTION
**Pull request by zivan**
This error was repeated in the same way
I suggest to add param nocheckcertificate -> wget::fetch to fix the error

### CODE REVIEW

**Comment by jhoblitt** [comment]
@zivan  Could you rebase on the current master to see if it resolves the travis failuers?

**Comment by zivan** [comment]
rebase done. travis builds is passing.

**Comment by zivan** [comment]
This is not PR merging. I am using vagrant with virtualbox (https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.5-64-puppet) I tried to install your puppet module (https://forge.puppetlabs.com/jhoblitt/selenium)

vagrant provision log
==> default: Notice: /Stage[main]/Selenium/Wget::Fetch[selenium-server-standalone]/Exec[wget-selenium-server-standalone]/returns: ERROR: certificate common name “*.googleusercontent.com” doesn’t match requested host name “selenium-release.storage.googleapis.com”.
==> default: Notice: /Stage[main]/Selenium/Wget::Fetch[selenium-server-standalone]/Exec[wget-selenium-server-standalone]/returns: To connect to selenium-release.storage.googleapis.com insecurely, use ‘--no-check-certificate’.
==> default: Error: wget --no-verbose --output-document='/opt/selenium/jars/selenium-server-standalone-2.44.0.jar' 'https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar' returned 5 instead of one of [0]
==> default: Error: /Stage[main]/Selenium/Wget::Fetch[selenium-server-standalone]/Exec[wget-selenium-server-standalone]/returns: change from notrun to 0 failed: wget --no-verbose --output-document='/opt/selenium/jars/selenium-server-standalone-2.44.0.jar' 'https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar' returned 5 instead of one of [0]

if do "wget https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar" from console on the guest
[vagrant@selenium ~]$ wget https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
--2015-01-15 03:17:44--  https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
Resolving selenium-release.storage.googleapis.com... 216.58.209.129, 2a00:1450:400f:803::100b
Connecting to selenium-release.storage.googleapis.com|216.58.209.129|:443... connected.
ERROR: certificate common name “*.googleusercontent.com” doesn’t match requested host name “selenium-release.storage.googleapis.com”.
To connect to selenium-release.storage.googleapis.com insecurely, use ‘--no-check-certificate’.

but on host machine ok

zivan@local:/tmp$ wget https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
--2015-01-15 09:20:26--  https://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
Resolving selenium-release.storage.googleapis.com (selenium-release.storage.googleapis.com)... 216.58.209.129, 2a00:1450:400f:804::2001
Connecting to selenium-release.storage.googleapis.com (selenium-release.storage.googleapis.com)|216.58.209.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35169724 (34M) [application/java-archive]
Saving to: ‘selenium-server-standalone-2.44.0.jar’

100%[=============================================================================================================>]


so i thought to add the param "nocheckcertificate"

**Comment by jhoblitt** [comment]
@zivan This looks good; could you add unit test coverage of the new param?

**Comment by zivan** [comment]
@jhoblitt  done please check

**Comment by jhoblitt** [comment]
@zivan looks good.  Thank you for the contribution!

**Pull request merged**
