### PR TITLE
Change the status case in debian initscript to be compatible with service resource type #59

### PR DESCRIPTION
**Pull request by marcgascon**

### CODE REVIEW

**Comment by marcgascon** [comment]
This pull request solves #59 

Could you check it and merge it @jhoblitt ? thanks!

**Comment by jhoblitt** [comment]
@marcgascon I want to put together some acceptance tests that cover the debian issue, since I don't use this module on that distro.  Please bare with me until the weekend.

**Comment by marcgascon** [comment]
Hi @jhoblitt,

Sorry but I was not at home this last weekend. I'm going to try to code some tests that covers this case. Thanks for your answer.

**Comment by marcgascon** [comment]
Sorry @jhoblitt but I don't know how to do the acceptance tests. Could you help me with that please?

**Comment by jhoblitt** [comment]
@marcgascon Could you rebase on master? I have added the acceptance tests to travis.

**Comment by marcgascon** [comment]
Ok done it.

**Comment by jhoblitt** [comment]
@marcgascon Looks good.  Thank you!

**Pull request merged**
