### PR TITLE
Manage users home

### PR DESCRIPTION
**Pull request by i11**
Some browsers don't like missing home directories...

### CODE REVIEW

**Comment by jhoblitt** [comment]
May I ask which browser is complianing?  I wonder if the homedir should be set to a path under the `$install_root`?

**Comment by i11** [comment]
Actually I'm not entirely sure that it's a browser that's causing problems. Most probably it's either selenium itself or a specific driver. So I got timeouts with firefox. The browser did start, but selenium refused to work with it. Standard error contained messages regarding not being able to access home directory. It worked flawlessly after home directory was created.

Here are some setup details:
RHEL7
xvfb
Selenium 2.46.0 (Java 1.8.0_51)
Firefox 39.0

**Comment by pinkypie** [comment]
:+1:

**Comment by tphoney** [comment]
:+1: from me to

**Comment by jhoblitt** [comment]
Any thoughts as to the correct location for the home dir? After some more consideration, I'm now leaning towards putting it under `/var`.  I'm also thinking the user and group should have `system` set.

**Comment by i11** [comment]
Personally I don't have any strong opinion on that. My nodes are mostly short living and dedicated for running only selenium, so it doesn't really matter where user home is. At least for now. On the other hand it can be changed right after the class definition by referring to the user by it's name.

Example:
```
User<| $title == 'selenium' |> {
  home => '/my/home/selenium',
}
```

Currently I do the same thing with ```managehome```, but it felt like this module should provide a working environment without having to fish for resource references.

Either way it's fine with me.

**Comment by tphoney** [comment]
puppet will put the homedir in the correct location, i dont think we need anything else apart from the default behaviour.

**Comment by jhoblitt** [comment]
@i11 Thanks for fixing this!  I'm going to merge this changeset as part of #51 with includes some test coverage and sets the default home to `/var/lib/selenium` so as to be consistent with other "system" role accounts.

**Comment by jhoblitt** [comment]
Released as part of [v1.1.0](https://forge.puppetlabs.com/jhoblitt/selenium/1.1.0).

**Pull request merged**
